# shellcheck shell=bash

module_final_summary() {
  echo "=== Done ==="
  echo "Adminer: http://<instance-ip>:8080 (constrain via Security Group)"

  echo "===================================================="
  echo "✅ Server Setup Complete - Ready for Laravel!"
  echo "===================================================="
  echo ""
  echo "🎯 QUICK START:"
  echo "  server-help  (or shelp)  - Show all available commands"
  echo "  server-info  (or sinfo)  - Show current server status"
  echo "  gkey                     - Display GitHub deploy key"
  echo ""
  echo "NEXT STEP: Install Laravel"
  echo "  Run: sudo setup-laravel"
  echo ""
  echo "This will create a new Laravel app with:"
  echo "  • Inertia.js + React starter kit"
  echo "  • PostgreSQL database (configured)"
  echo "  • Redis cache/sessions (configured)"
  echo "  • Mailpit email testing (configured)"
  echo "  • Laravel Cashier for Stripe payments"
  echo "  • AWS SDK for S3, SES, etc."
  echo "  • Spatie Laravel Data (DTOs with validation)"
  echo "  • Spatie TypeScript Transformer (full-stack type safety)"
  echo "  • Spatie Laravel Permission (roles & permissions)"
  echo "  • Spatie Laravel Activity Log (audit logging)"
  echo "  • Spatie Laravel Media Library (file management)"
  echo "  • Spatie Laravel PDF (PDF generation)"
  echo "  • Git repository initialized"
  echo "  • Pest testing framework"
  echo "  • Laravel Telescope debugging dashboard"
  echo ""
  echo "Database credentials: /home/ubuntu/.db_credentials"
  echo "Adminer (database UI): http://$(curl -s ifconfig.me 2>/dev/null || echo 'your-ip'):8080"
  echo "Mailpit (email testing): http://$(curl -s ifconfig.me 2>/dev/null || echo 'your-ip'):8025"
  echo "GitHub deploy key: Run 'gkey' to view"
  echo ""
  echo "After Laravel installation:"
  echo "  1. cd /var/www/html"
  echo "  2. vdev (starts Vite dev server with HMR)"
  echo "  3. Visit: http://$(curl -s ifconfig.me 2>/dev/null || echo 'your-ip')"
  echo "  4. deploy (run full production build)"
  echo ""
  echo "For SSL setup (after DNS):"
  echo "  setup-ssl yourdomain.com your@email.com"
  echo "===================================================="
}

register_step module_final_summary
